import { Injectable } from '@angular/core';
import { MatSnackBar } from '@angular/material/snack-bar';
import { Language } from './models/language';

interface LanguageStrings {
  [key: string]: string;
}

interface StringResources {
  [key: string]: LanguageStrings;
}

@Injectable({
  providedIn: 'root',
})
export class Constants {
  constructor() {}

  languages: Language[] = [
    { name: 'Arabic', emoji: '🇸🇦' },
    { name: 'English', emoji: '🇬🇧' },
    { name: 'French', emoji: '🇫🇷' },
    { name: 'German', emoji: '🇩🇪' },
    { name: 'Hindi', emoji: '🇮🇳' },
    { name: 'Italian', emoji: '🇮🇹' },
    { name: 'Mandarin Chinese (Simplified)', emoji: '🇨🇳' },
    { name: 'Portuguese', emoji: '🇵🇹' },
    { name: 'Russian', emoji: '🇷🇺' },
    { name: 'Spanish', emoji: '🇪🇸' },
  ];

  genres: Language[] = [
    { name: 'adventure', emoji: '🌍' },
    { name: 'animalStories', emoji: '🐾' },
    { name: 'comedy', emoji: '🎭' },
    { name: 'fairyTale', emoji: '🏰' },
    { name: 'fantasy', emoji: '🐉' },
    { name: 'historicalFiction', emoji: '🏛' },
    { name: 'mystery', emoji: '🔍' },
    { name: 'scienceFiction', emoji: '🚀' },
    { name: 'superhero', emoji: '🦸' },
  ];

  strings: StringResources = {
    generateStory: {
      English: 'Generate Story',
      'Mandarin Chinese (Simplified)': '生成故事',
      Hindi: 'कहानी उत्पन्न करें',
      Spanish: 'Generar historia',
      French: 'Générer une histoire',
      Arabic: 'توليد قصة',
      Russian: 'Создать историю',
      Portuguese: 'Gerar história',
      Italian: 'Genera Storia',
      German: 'Geschichte generieren',
    },
    refreshBrowser: {
      English: 'Refresh for a new story',
      'Mandarin Chinese (Simplified)': '刷新浏览器以获取新故事',
      Hindi: 'नई कहानी के लिए ब्राउज़र रीफ़्रेश करें',
      Spanish: 'Refresca el navegador para obtener una nueva historia',
      French: 'Rafraîchir le navigateur pour une nouvelle histoire',
      Arabic: 'تحديث المتصفح للحصول على قصة جديدة',
      Russian: 'Обновите браузер для новой истории',
      Portuguese: 'Atualize o navegador para uma nova história',
      Italian: 'Aggiorna per una nuova storia',
      German: 'Aktualisieren für eine neue Geschichte',
    },
    optionA: {
      English: 'Option A',
      'Mandarin Chinese (Simplified)': '选项A',
      Hindi: 'विकल्प A',
      Spanish: 'Opción A',
      French: 'Option A',
      Arabic: 'الخيار A',
      Russian: 'Опция A',
      Portuguese: 'Opção A',
      Italian: 'Opzione A',
      German: 'Option A',
    },
    optionB: {
      English: 'Option B',
      'Mandarin Chinese (Simplified)': '选项B',
      Hindi: 'विकल्प B',
      Spanish: 'Opción B',
      French: 'Option B',
      Arabic: 'الخيار B',
      Russian: 'Опция B',
      Portuguese: 'Opção B',
      Italian: 'Opzione B',
      German: 'Option B',
    },
    chapter: {
      English: 'Chapter',
      'Mandarin Chinese (Simplified)': '章',
      Hindi: 'अध्याय',
      Spanish: 'Capítulo',
      French: 'Chapitre',
      Arabic: 'الفصل',
      Russian: 'Глава',
      Portuguese: 'Capítulo',
      Italian: 'Capitolo',
      German: 'Kapitel',
    },
    play: {
      English: 'Play',
      'Mandarin Chinese (Simplified)': '播放',
      Hindi: 'चलाएं',
      Spanish: 'Reproducir',
      French: 'Jouer',
      Arabic: 'تشغيل',
      Russian: 'Воспроизвести',
      Portuguese: 'Reproduzir',
      Italian: 'Riproduci',
      German: 'Abspielen',
    },
    preparingYourLiteraryJourney: {
      English: 'Preparing your literary journey...',
      'Mandarin Chinese (Simplified)': '准备您的文学之旅...',
      Hindi: 'आपकी साहित्यिक यात्रा तैयार कर रहे हैं...',
      Spanish: 'Preparando tu viaje literario...',
      French: 'Préparation de votre voyage littéraire...',
      Arabic: 'إعداد رحلتك الأدبية...',
      Russian: 'Подготовка вашего литературного путешествия...',
      Portuguese: 'Preparando sua jornada literária...',
      Italian: 'Preparazione del tuo viaggio letterario...',
      German: 'Vorbereitung Ihrer literarischen Reise...',
    },
    generatingStoryline: {
      English: 'Generating storyline...',
      'Mandarin Chinese (Simplified)': '生成故事情节...',
      Hindi: 'कहानी उत्पन्न कर रहे हैं...',
      Spanish: 'Generando argumento...',
      French: "Génération de l'intrigue...",
      Arabic: 'توليد القصة...',
      Russian: 'Создание сюжета...',
      Portuguese: 'Gerando enredo...',
      Italian: 'Generazione della trama...',
      German: 'Erzeuge Handlungsstrang...',
    },
    warmingUpTheNarrator: {
      English: 'Warming up the narrator...',
      'Mandarin Chinese (Simplified)': '预热叙述者...',
      Hindi: 'नैरेटर को गरम कर रहे हैं...',
      Spanish: 'Calentando al narrador...',
      French: 'Échauffement du narrateur...',
      Arabic: 'تحمية الراوي...',
      Russian: 'Разогрев нарратора...',
      Portuguese: 'Aquecendo o narrador...',
      Italian: 'Scaldando il narratore...',
      German: 'Den Erzähler aufwärmen...',
    },
    generatingAudio: {
      English: 'Generating audio...',
      'Mandarin Chinese (Simplified)': '生成音频...',
      Hindi: 'ऑडियो उत्पन्न कर रहे हैं...',
      Spanish: 'Generando audio...',
      French: "Génération de l'audio...",
      Arabic: 'توليد الصوت...',
      Russian: 'Создание аудио...',
      Portuguese: 'Gerando áudio...',
      Italian: "Generazione dell'audio...",
      German: 'Audio generieren...',
    },
    sprinklingSomeFairyDust: {
      English: 'Sprinkling some fairy dust...',
      'Mandarin Chinese (Simplified)': '撒些仙女粉...',
      Hindi: 'परी की धूल छिड़क रहे हैं...',
      Spanish: 'Espolvoreando polvo de hadas...',
      French: 'Saupoudrage de poussière de fée...',
      Arabic: 'رش بعض غبار الجنية...',
      Russian: 'Посыпание волшебной пылью...',
      Portuguese: 'Espalhando pó de fada...',
      Italian: "Spargendo un po' di polvere di fata...",
      German: 'Ein wenig Feenstaub streuen...',
    },
    tuningIntoTheFrequencyOfAdventure: {
      English: 'Tuning into the frequency of adventure...',
      'Mandarin Chinese (Simplified)': '调整到冒险的频率...',
      Hindi: 'साहसिक कार्य की फ्रीक्वेंसी में ट्यून कर रहे हैं...',
      Spanish: 'Sintonizando la frecuencia de la aventura...',
      French: "Se caler sur la fréquence de l'aventure...",
      Arabic: 'التناغم مع تردد المغامرة...',
      Russian: 'Настройка на частоту приключений...',
      Portuguese: 'Sintonizando na frequência da aventura...',
      Italian: "Sintonizzarsi sulla frequenza dell'avventura...",
      German: 'Abstimmen auf die Abenteuerfrequenz...',
    },
    brewingUpSomeEpicTales: {
      English: 'Brewing up some epic tales...',
      'Mandarin Chinese (Simplified)': '酝酿一些史诗般的故事...',
      Hindi: 'कुछ महाकाव्य कथाएँ तैयार कर रहे हैं...',
      Spanish: 'Cocinando algunos cuentos épicos...',
      French: 'Préparation de quelques récits épiques...',
      Arabic: 'يخمر بعض الحكايات الملحمية...',
      Russian: 'Завариваем эпические истории...',
      Portuguese: 'Preparando alguns contos épicos...',
      Italian: 'Preparando alcune epiche storie...',
      German: 'Einige epische Geschichten brauen...',
    },
    queuingTheSuspense: {
      English: 'Queuing the suspense...',
      'Mandarin Chinese (Simplified)': '排队等候悬疑...',
      Hindi: 'सस्पेंस को कतार में लगा रहे हैं...',
      Spanish: 'En cola para el suspense...',
      French: "Mise en file d'attente du suspense...",
      Arabic: 'تصف الإثارة...',
      Russian: 'Строим очередь на напряжение...',
      Portuguese: 'Enfileirando o suspense...',
      Italian: 'Mettere in coda il suspense...',
      German: 'Spannung in der Warteschlange...',
    },
    fairyTale: {
      English: 'Fairy Tale',
      'Mandarin Chinese (Simplified)': '童话',
      Hindi: 'परी कथा',
      Spanish: 'Cuento de hadas',
      French: 'Conte de fées',
      Arabic: 'حكاية خرافية',
      Russian: 'Сказка',
      Portuguese: 'Conto de fadas',
      Italian: 'Fiaba',
      German: 'Märchen',
    },
    fantasy: {
      English: 'Fantasy',
      'Mandarin Chinese (Simplified)': '幻想',
      Hindi: 'कल्पना',
      Spanish: 'Fantasía',
      French: 'Fantaisie',
      Arabic: 'خيال',
      Russian: 'Фэнтези',
      Portuguese: 'Fantasia',
      Italian: 'Fantasia',
      German: 'Fantasie',
    },
    adventure: {
      English: 'Adventure',
      'Mandarin Chinese (Simplified)': '冒险',
      Hindi: 'साहसिक',
      Spanish: 'Aventura',
      French: 'Aventure',
      Arabic: 'مغامرة',
      Russian: 'Приключение',
      Portuguese: 'Aventura',
      Italian: 'Avventura',
      German: 'Abenteuer',
    },
    scienceFiction: {
      English: 'Science Fiction',
      'Mandarin Chinese (Simplified)': '科幻',
      Hindi: 'विज्ञान कथा',
      Spanish: 'Ciencia ficción',
      French: 'Science-fiction',
      Arabic: 'خيال علمي',
      Russian: 'Научная фантастика',
      Portuguese: 'Ficção científica',
      Italian: 'Fantascienza',
      German: 'Science-Fiction',
    },
    mystery: {
      English: 'Mystery',
      'Mandarin Chinese (Simplified)': '神秘',
      Hindi: 'रहस्य',
      Spanish: 'Misterio',
      French: 'Mystère',
      Arabic: 'غموض',
      Russian: 'Мистерия',
      Portuguese: 'Mistério',
      Italian: 'Mistero',
      German: 'Mysterium',
    },
    animalStories: {
      English: 'Animal Stories',
      'Mandarin Chinese (Simplified)': '动物故事',
      Hindi: 'पशु कथाएँ',
      Spanish: 'Historias de animales',
      French: "Histoires d'animaux",
      Arabic: 'قصص الحيوانات',
      Russian: 'Животные истории',
      Portuguese: 'Histórias de animais',
      Italian: 'Storie di animali',
      German: 'Tiergeschichten',
    },
    historicalFiction: {
      English: 'Historical Fiction',
      'Mandarin Chinese (Simplified)': '历史小说',
      Hindi: 'ऐतिहासिक कल्पना',
      Spanish: 'Ficción histórica',
      French: 'Fiction historique',
      Arabic: 'رواية تاريخية',
      Russian: 'Историческая фантастика',
      Portuguese: 'Ficção histórica',
      Italian: 'Narrativa storica',
      German: 'Historischer Roman',
    },
    comedy: {
      English: 'Comedy',
      'Mandarin Chinese (Simplified)': '喜剧',
      Hindi: 'कॉमेडी',
      Spanish: 'Comedia',
      French: 'Comédie',
      Arabic: 'كوميديا',
      Russian: 'Комедия',
      Portuguese: 'Comédia',
      Italian: 'Commedia',
      German: 'Komödie',
    },
    superhero: {
      English: 'Superhero',
      'Mandarin Chinese (Simplified)': '超级英雄',
      Hindi: 'सुपरहीरो',
      Spanish: 'Superhéroe',
      French: 'Super-héros',
      Arabic: 'بطل خارق',
      Russian: 'Супергерой',
      Portuguese: 'Super-herói',
      Italian: 'Supereroe',
      German: 'Superheld',
    },
  };
}
